### ISSUE TITLE
[BUG] Deployment issues

### ISSUE THREAD

**Issue by JMGaljaard** [DiegoStock12/kubeml#1]
Hi @DiegoStock12, thank you for the excellent repo, I plan on using it for the CS4290 course. While walking through your setup guide, I found a few minor issues that might be work noting. 

 1. It would be nice to add the command and install the helm chart through the fission repository (after updating with `helm update repo`).
 ```bash
helm repo add fission-charts https://fission.github.io/fission-charts/
``` 

 2. The command `helm repo add stable https://kubernetes-charts.storage.googleapis.com/` no longer works (see issue [#19279](https://github.com/helm/charts/issues/19279)). Instead the following command should be used: 
 ```bash 
helm repo add stable https://charts.helm.sh/stable
```

 3. The docker repository `redisai/redisai` now returns a 404, I think the image should be pulled from `redislabs/redisai` (see also [redisai README](https://github.com/RedisAI/RedisAI#docker). (I found this only after re-generating my docker login tokens, and getting this error in kubernetes dashboard):
 ```
 Failed to pull image "redisai/redisai:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for redisai/redisai, repository does not exist or may require 'docker login': denied: requested access to the resource is denied 
 ```
4. Lastly, it might be nice to notify that it is advisable to run `docker  login` when deploying locally (e.g. when using `minikube`).

**Comment by DiegoStock12** [comment]
Hi! Thank you for the message. It might be true that some of the things changed.

I'll try today to deploy it from zero and make sure that everything works, and then refresh everything.

I'll also make available a couple of scripts so everything is even more automated

**Comment by JMGaljaard** [comment]
Thank you for the quick response! Excellent!

**Comment by DiegoStock12** [comment]
Hi again! I fixed the issues with the commands. They must have changed the nomenclature for the redis image recently, since two weeks ago I deployed without problems. But everything is tested now.

I think docker login should not be necessary since all the images are public, so it should work well without the need of it.

Also I added a note, If you want to run on GPU a better alternative is MicroK8s, especially if you're running Linux. There you can activate the GPU support with a single command.

**Comment by DiegoStock12** [comment]
Finally, there is the cluster_config script in the ml/hack directory, so once you have all the helm repos in your local machine you can just run that and automate the entire deployment process

**Comment by DiegoStock12** [comment]
And tell me if you find any other issue that I can solve!

**Comment by JMGaljaard** [comment]
Excellent, I ran through the process again and all pods spin up successfully. Apparently I ran into Dockers rate limiting policy due to pulling some images before spinning up the cluster
